-- Seed data: 401 Billboard Top 10 hits from the 1980s
-- Run this in the Neon SQL Editor after running schema.sql

INSERT INTO songs (title, artist, tags, year, mood, tempo, category) VALUES
  ('Call Me', 'Blondie', ARRAY['new wave', 'disco', 'movie soundtrack'], 1980, 'bright', 'mid', '80s_top10'),
  ('Another Brick in the Wall (Part 2)', 'Pink Floyd', ARRAY['pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Magic', 'Olivia Newton-John', ARRAY['pop', 'soft rock', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Rock With You', 'Michael Jackson', ARRAY['pop', 'disco', 'funk', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('Do That to Me One More Time', 'Captain & Tennille', ARRAY['pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Crazy Little Thing Called Love', 'Queen', ARRAY['rockabilly', 'rock', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('Another One Bites the Dust', 'Queen', ARRAY['rock', 'funk', 'disco'], 1980, 'bright', 'fast', '80s_top10'),
  ('Funkytown', 'Lipps, Inc.', ARRAY['disco', 'funk', 'synth', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('It''s Still Rock and Roll to Me', 'Billy Joel', ARRAY['pop rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Upside Down', 'Diana Ross', ARRAY['disco', 'pop', 'dance', 'Chic'], 1980, 'bright', 'fast', '80s_top10'),
  ('Please Don''t Go', 'KC & The Sunshine Band', ARRAY['disco', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Woman in Love', 'Barbra Streisand', ARRAY['pop', 'ballad', 'romantic'], 1980, 'romantic', 'slow', '80s_top10'),
  ('Lady', 'Kenny Rogers', ARRAY['country pop', 'ballad', 'romantic', 'soft'], 1980, 'romantic', 'slow', '80s_top10'),
  ('Celebration', 'Kool & The Gang', ARRAY['funk', 'disco', 'party'], 1980, 'bright', 'fast', '80s_top10'),
  ('Sailing', 'Christopher Cross', ARRAY['soft rock', 'yacht rock', 'mellow'], 1980, 'dreamy', 'slow', '80s_top10'),
  ('Coming Up (Live at Glasgow)', 'Paul McCartney', ARRAY['pop rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('(Just Like) Starting Over', 'John Lennon', ARRAY['pop rock', 'retro', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('9 to 5', 'Dolly Parton', ARRAY['country pop', 'movie soundtrack', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('I Love a Rainy Night', 'Eddie Rabbitt', ARRAY['country pop', 'crossover', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('All Out of Love', 'Air Supply', ARRAY['soft rock', 'ballad', 'romantic'], 1980, 'romantic', 'slow', '80s_top10'),
  ('Ride Like the Wind', 'Christopher Cross', ARRAY['soft rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Longer', 'Dan Fogelberg', ARRAY['soft rock', 'ballad', 'romantic'], 1980, 'romantic', 'slow', '80s_top10'),
  ('Lost in Love', 'Air Supply', ARRAY['soft rock', 'ballad', 'romantic'], 1980, 'romantic', 'slow', '80s_top10'),
  ('The Rose', 'Bette Midler', ARRAY['pop', 'ballad', 'movie soundtrack'], 1980, 'romantic', 'slow', '80s_top10'),
  ('The Wanderer', 'Donna Summer', ARRAY['rock', 'new wave', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('Little Jeannie', 'Elton John', ARRAY['pop', 'soft rock', 'romantic'], 1980, 'romantic', 'mid', '80s_top10'),
  ('He''s So Shy', 'Pointer Sisters', ARRAY['pop', 'R&B', 'fun', 'catchy'], 1980, 'bright', 'fast', '80s_top10'),
  ('Emotional Rescue', 'The Rolling Stones', ARRAY['rock', 'disco', 'funk'], 1980, 'bright', 'fast', '80s_top10'),
  ('Fame', 'Irene Cara', ARRAY['pop', 'disco', 'movie soundtrack', 'anthem'], 1980, 'triumphant', 'mid', '80s_top10'),
  ('Give Me the Night', 'George Benson', ARRAY['R&B', 'jazz', 'funk'], 1980, 'bright', 'fast', '80s_top10'),
  ('Against the Wind', 'Bob Seger & The Silver Bullet Band', ARRAY['rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Hungry Heart', 'Bruce Springsteen', ARRAY['pop rock', 'heartland rock', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('I''m Coming Out', 'Diana Ross', ARRAY['disco', 'pop', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('On the Radio', 'Donna Summer', ARRAY['disco', 'pop', 'dance', 'romantic'], 1980, 'romantic', 'fast', '80s_top10'),
  ('Sexy Eyes', 'Dr. Hook', ARRAY['pop rock', 'soft rock', 'flirty', 'fun'], 1980, 'bright', 'fast', '80s_top10'),
  ('Drivin'' My Life Away', 'Eddie Rabbitt', ARRAY['country pop', 'crossover', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('Lookin'' for Love', 'Johnny Lee', ARRAY['country pop', 'movie soundtrack', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('Master Blaster (Jammin'')', 'Stevie Wonder', ARRAY['reggae', 'R&B', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('Passion', 'Rod Stewart', ARRAY['pop rock', 'new wave', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('Late in the Evening', 'Paul Simon', ARRAY['pop', 'Latin', 'horn section'], 1980, 'bright', 'mid', '80s_top10'),
  ('Steal Away', 'Robbie Dupree', ARRAY['soft rock', 'yacht rock', 'mellow'], 1980, 'dreamy', 'slow', '80s_top10'),
  ('You May Be Right', 'Billy Joel', ARRAY['pop rock', 'energetic', 'fun'], 1980, 'bright', 'fast', '80s_top10'),
  ('I''m Alright', 'Kenny Loggins', ARRAY['pop rock', 'movie soundtrack', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('I Can''t Tell You Why', 'Eagles', ARRAY['soft rock', 'R&B', 'ballad'], 1980, 'romantic', 'slow', '80s_top10'),
  ('Xanadu', 'Olivia Newton-John & ELO', ARRAY['disco', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Cars', 'Gary Numan', ARRAY['synth pop', 'new wave', 'electronic'], 1980, 'bright', 'mid', '80s_top10'),
  ('Hit Me with Your Best Shot', 'Pat Benatar', ARRAY['pop rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Let My Love Open the Door', 'Pete Townshend', ARRAY['pop rock', 'pop', '1980s'], 1980, 'bright', 'mid', '80s_top10'),
  ('Hey Nineteen', 'Steely Dan', ARRAY['soft rock', 'jazz rock', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('De Do Do Do, De Da Da Da', 'The Police', ARRAY['new wave', 'reggae pop', 'pop'], 1980, 'bright', 'mid', '80s_top10'),
  ('Off the Wall', 'Michael Jackson', ARRAY['disco', 'funk', 'pop', 'dance'], 1980, 'bright', 'fast', '80s_top10'),
  ('She''s Out of My Life', 'Michael Jackson', ARRAY['pop', 'ballad', 'sad'], 1980, 'melancholy', 'slow', '80s_top10'),
  ('Too Hot', 'Kool & The Gang', ARRAY['funk', 'disco', 'dance', 'groovy'], 1980, 'bright', 'fast', '80s_top10'),
  ('Physical', 'Olivia Newton-John', ARRAY['pop', 'dance', 'provocative'], 1981, 'bright', 'fast', '80s_top10'),
  ('Bette Davis Eyes', 'Kim Carnes', ARRAY['pop rock', 'new wave', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Endless Love', 'Diana Ross & Lionel Richie', ARRAY['pop', 'ballad', '1981s'], 1981, 'romantic', 'slow', '80s_top10'),
  ('Jessie''s Girl', 'Rick Springfield', ARRAY['pop rock', 'new wave', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Keep On Loving You', 'REO Speedwagon', ARRAY['arena rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('The Tide Is High', 'Blondie', ARRAY['pop', 'reggae', 'new wave'], 1981, 'bright', 'mid', '80s_top10'),
  ('Rapture', 'Blondie', ARRAY['new wave', 'rap', 'dance', 'experimental'], 1981, 'bright', 'fast', '80s_top10'),
  ('The One That You Love', 'Air Supply', ARRAY['soft rock', 'ballad', 'pop'], 1981, 'romantic', 'slow', '80s_top10'),
  ('Kiss on My List', 'Daryl Hall & John Oates', ARRAY['pop rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Private Eyes', 'Daryl Hall & John Oates', ARRAY['pop rock', 'new wave', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Arthur''s Theme (Best That You Can Do)', 'Christopher Cross', ARRAY['pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Morning Train (Nine to Five)', 'Sheena Easton', ARRAY['pop', 'dance pop', '1981s'], 1981, 'bright', 'fast', '80s_top10'),
  ('Chariots of Fire', 'Vangelis', ARRAY['synth', 'instrumental', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Waiting for a Girl Like You', 'Foreigner', ARRAY['arena rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Start Me Up', 'The Rolling Stones', ARRAY['rock', 'hard rock', 'pop'], 1981, 'energetic', 'mid', '80s_top10'),
  ('Queen of Hearts', 'Juice Newton', ARRAY['country pop', 'rockabilly', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Woman', 'John Lennon', ARRAY['pop', 'ballad', 'romantic', 'tribute'], 1981, 'romantic', 'slow', '80s_top10'),
  ('Slow Hand', 'Pointer Sisters', ARRAY['pop', 'R&B', 'romantic', 'sultry'], 1981, 'romantic', 'mid', '80s_top10'),
  ('Just the Two of Us', 'Grover Washington Jr. with Bill Withers', ARRAY['pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Being with You', 'Smokey Robinson', ARRAY['R&B', 'pop', 'romantic'], 1981, 'romantic', 'mid', '80s_top10'),
  ('Love on the Rocks', 'Neil Diamond', ARRAY['pop', 'soft rock', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('All Those Years Ago', 'George Harrison', ARRAY['pop rock', 'tribute', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Let''s Groove', 'Earth, Wind & Fire', ARRAY['funk', 'disco', 'dance'], 1981, 'bright', 'fast', '80s_top10'),
  ('Harden My Heart', 'Quarterflash', ARRAY['pop rock', 'new wave', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Stop Draggin'' My Heart Around', 'Stevie Nicks with Tom Petty', ARRAY['pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('The Best of Times', 'Styx', ARRAY['arena rock', 'power ballad', 'pop'], 1981, 'romantic', 'slow', '80s_top10'),
  ('Every Little Thing She Does Is Magic', 'The Police', ARRAY['new wave', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Urgent', 'Foreigner', ARRAY['arena rock', 'saxophone', 'energetic'], 1981, 'energetic', 'fast', '80s_top10'),
  ('Who''s Crying Now', 'Journey', ARRAY['arena rock', 'power ballad', 'pop'], 1981, 'romantic', 'slow', '80s_top10'),
  ('Angel of the Morning', 'Juice Newton', ARRAY['country pop', 'soft rock', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('You Make My Dreams', 'Daryl Hall & John Oates', ARRAY['pop rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Take It on the Run', 'REO Speedwagon', ARRAY['arena rock', 'pop rock', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Young Turks', 'Rod Stewart', ARRAY['pop rock', 'new wave', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('Elvira', 'Oak Ridge Boys', ARRAY['country', 'novelty', 'fun', 'catchy'], 1981, 'bright', 'fast', '80s_top10'),
  ('Step by Step', 'Eddie Rabbitt', ARRAY['country pop', 'dance', 'pop'], 1981, 'bright', 'fast', '80s_top10'),
  ('Don''t Stop Believin''', 'Journey', ARRAY['arena rock', 'anthem', 'pop'], 1981, 'triumphant', 'mid', '80s_top10'),
  ('Hard to Say', 'Dan Fogelberg', ARRAY['soft rock', 'ballad', 'romantic'], 1981, 'romantic', 'slow', '80s_top10'),
  ('While You See a Chance', 'Steve Winwood', ARRAY['pop rock', 'synth', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('The Winner Takes It All', 'ABBA', ARRAY['pop', 'ballad', 'dramatic'], 1981, 'romantic', 'slow', '80s_top10'),
  ('America', 'Neil Diamond', ARRAY['pop', 'patriotic', 'anthem', 'dramatic'], 1981, 'triumphant', 'mid', '80s_top10'),
  ('Hold on Tight', 'Electric Light Orchestra', ARRAY['pop rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Don''t Stand So Close to Me', 'The Police', ARRAY['new wave', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Watching the Wheels', 'John Lennon', ARRAY['pop', 'reflective', 'gentle'], 1981, 'reflective', 'slow', '80s_top10'),
  ('Same Old Lang Syne', 'Dan Fogelberg', ARRAY['soft rock', 'storytelling', 'pop'], 1981, 'bright', 'mid', '80s_top10'),
  ('I''ve Done Everything for You', 'Rick Springfield', ARRAY['pop rock', 'pop', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('Hello Again', 'Neil Diamond', ARRAY['pop', 'soft rock', '1981s'], 1981, 'bright', 'mid', '80s_top10'),
  ('I Love Rock ''N'' Roll', 'Joan Jett & The Blackhearts', ARRAY['rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Eye of the Tiger', 'Survivor', ARRAY['arena rock', 'movie soundtrack', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Centerfold', 'J. Geils Band', ARRAY['pop rock', 'new wave', 'fun'], 1982, 'bright', 'fast', '80s_top10'),
  ('Ebony and Ivory', 'Paul McCartney & Stevie Wonder', ARRAY['pop', 'duet', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Jack & Diane', 'John Cougar Mellencamp', ARRAY['heartland rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Hard to Say I''m Sorry', 'Chicago', ARRAY['soft rock', 'ballad', 'pop'], 1982, 'romantic', 'slow', '80s_top10'),
  ('Don''t You Want Me', 'The Human League', ARRAY['synth pop', 'new wave', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Maneater', 'Daryl Hall & John Oates', ARRAY['pop rock', 'new wave', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('I Can''t Go for That (No Can Do)', 'Daryl Hall & John Oates', ARRAY['pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Abracadabra', 'Steve Miller Band', ARRAY['pop rock', 'synth', 'playful'], 1982, 'bright', 'mid', '80s_top10'),
  ('Up Where We Belong', 'Joe Cocker & Jennifer Warnes', ARRAY['pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Truly', 'Lionel Richie', ARRAY['R&B', 'pop ballad', 'romantic', 'smooth'], 1982, 'romantic', 'slow', '80s_top10'),
  ('Down Under', 'Men at Work', ARRAY['new wave', 'pop rock', 'fun'], 1982, 'bright', 'fast', '80s_top10'),
  ('Who Can It Be Now?', 'Men at Work', ARRAY['new wave', 'pop rock', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Mickey', 'Toni Basil', ARRAY['pop', 'cheerleader', 'dance', 'novelty'], 1982, 'bright', 'fast', '80s_top10'),
  ('Hurts So Good', 'John Cougar Mellencamp', ARRAY['heartland rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Open Arms', 'Journey', ARRAY['arena rock', 'power ballad', 'romantic'], 1982, 'romantic', 'slow', '80s_top10'),
  ('Gloria', 'Laura Branigan', ARRAY['pop', 'dance', 'dramatic', 'powerful'], 1982, 'bright', 'fast', '80s_top10'),
  ('We Got the Beat', 'Go-Go''s', ARRAY['new wave', 'pop rock', 'fun'], 1982, 'bright', 'fast', '80s_top10'),
  ('Shame on the Moon', 'Bob Seger & The Silver Bullet Band', ARRAY['rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Rosanna', 'Toto', ARRAY['pop rock', 'R&B', 'sophisticated', 'groovy'], 1982, 'bright', 'mid', '80s_top10'),
  ('Don''t Talk to Strangers', 'Rick Springfield', ARRAY['pop rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Eye in the Sky', 'Alan Parsons Project', ARRAY['art rock', 'synth pop', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Tainted Love', 'Soft Cell', ARRAY['synth pop', 'new wave', 'dark'], 1982, 'melancholy', 'mid', '80s_top10'),
  ('Heat of the Moment', 'Asia', ARRAY['progressive rock', 'arena rock', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Shake It Up', 'The Cars', ARRAY['new wave', 'pop rock', 'dance'], 1982, 'bright', 'fast', '80s_top10'),
  ('867-5309/Jenny', 'Tommy Tutone', ARRAY['pop rock', 'power pop', 'catchy'], 1982, 'bright', 'mid', '80s_top10'),
  ('Hold Me', 'Fleetwood Mac', ARRAY['pop rock', 'soft rock', 'romantic'], 1982, 'romantic', 'mid', '80s_top10'),
  ('Freeze-Frame', 'J. Geils Band', ARRAY['pop rock', 'new wave', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Stray Cat Strut', 'Stray Cats', ARRAY['rockabilly', 'retro', 'cool'], 1982, 'bright', 'mid', '80s_top10'),
  ('Always on My Mind', 'Willie Nelson', ARRAY['country', 'ballad', 'pop'], 1982, 'romantic', 'slow', '80s_top10'),
  ('Back on the Chain Gang', 'The Pretenders', ARRAY['new wave', 'pop rock', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Heartlight', 'Neil Diamond', ARRAY['pop', 'soft rock', 'movie inspired'], 1982, 'bright', 'mid', '80s_top10'),
  ('Let It Whip', 'Dazz Band', ARRAY['funk', 'R&B', 'dance', 'groovy'], 1982, 'bright', 'fast', '80s_top10'),
  ('Steppin'' Out', 'Joe Jackson', ARRAY['new wave', 'jazz pop', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Leather and Lace', 'Stevie Nicks with Don Henley', ARRAY['soft rock', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Vacation', 'Go-Go''s', ARRAY['new wave', 'pop rock', 'fun', 'summer'], 1982, 'bright', 'fast', '80s_top10'),
  ('I Ran (So Far Away)', 'A Flock of Seagulls', ARRAY['synth pop', 'pop', '1982s'], 1982, 'bright', 'mid', '80s_top10'),
  ('Leader of the Band', 'Dan Fogelberg', ARRAY['soft rock', 'folk', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Rock This Town', 'Stray Cats', ARRAY['rockabilly', 'retro', 'energetic'], 1982, 'energetic', 'fast', '80s_top10'),
  ('Only the Lonely', 'The Motels', ARRAY['new wave', 'synth pop', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Caught Up in You', '38 Special', ARRAY['southern rock', 'arena rock', 'pop'], 1982, 'bright', 'mid', '80s_top10'),
  ('Muscles', 'Diana Ross', ARRAY['pop', 'R&B', 'fun'], 1982, 'bright', 'fast', '80s_top10'),
  ('Pass the Dutchie', 'Musical Youth', ARRAY['reggae', 'pop', 'novelty'], 1982, 'playful', 'mid', '80s_top10'),
  ('Get Down on It', 'Kool & The Gang', ARRAY['funk', 'disco', 'dance'], 1982, 'bright', 'fast', '80s_top10'),
  ('Every Breath You Take', 'The Police', ARRAY['new wave', 'pop rock', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('Billie Jean', 'Michael Jackson', ARRAY['pop', 'dance', 'funk', 'iconic'], 1983, 'bright', 'fast', '80s_top10'),
  ('Flashdance... What a Feeling', 'Irene Cara', ARRAY['pop', 'dance', '1983s'], 1983, 'bright', 'fast', '80s_top10'),
  ('Say Say Say', 'Paul McCartney & Michael Jackson', ARRAY['pop', 'duet', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('All Night Long (All Night)', 'Lionel Richie', ARRAY['pop', 'world music', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Total Eclipse of the Heart', 'Bonnie Tyler', ARRAY['power ballad', 'pop', '1983s'], 1983, 'romantic', 'slow', '80s_top10'),
  ('Beat It', 'Michael Jackson', ARRAY['pop', 'rock crossover', 'tough'], 1983, 'energetic', 'mid', '80s_top10'),
  ('Come On Eileen', 'Dexys Midnight Runners', ARRAY['new wave', 'Celtic', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('Maniac', 'Michael Sembello', ARRAY['pop', 'synth', 'movie soundtrack'], 1983, 'bright', 'mid', '80s_top10'),
  ('Baby, Come to Me', 'Patti Austin & James Ingram', ARRAY['R&B', 'pop', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Africa', 'Toto', ARRAY['pop rock', 'world music', 'atmospheric'], 1983, 'dreamy', 'mid', '80s_top10'),
  ('Sweet Dreams (Are Made of This)', 'Eurythmics', ARRAY['synth pop', 'pop', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Islands in the Stream', 'Kenny Rogers & Dolly Parton', ARRAY['pop', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Tell Her About It', 'Billy Joel', ARRAY['pop', 'Motown inspired', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Wanna Be Startin'' Somethin''', 'Michael Jackson', ARRAY['pop', 'funk', '1983s'], 1983, 'bright', 'fast', '80s_top10'),
  ('Shame on the Moon', 'Bob Seger', ARRAY['rock', 'country rock', 'mellow'], 1983, 'dreamy', 'slow', '80s_top10'),
  ('Let''s Dance', 'David Bowie', ARRAY['pop', 'dance', 'funk', 'reinvention'], 1983, 'bright', 'fast', '80s_top10'),
  ('She Works Hard for the Money', 'Donna Summer', ARRAY['pop', 'dance', '1983s'], 1983, 'bright', 'fast', '80s_top10'),
  ('Mr. Roboto', 'Styx', ARRAY['synth rock', 'concept', 'robotic'], 1983, 'bright', 'mid', '80s_top10'),
  ('Do You Really Want to Hurt Me', 'Culture Club', ARRAY['new wave', 'pop', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Hungry Like the Wolf', 'Duran Duran', ARRAY['new wave', 'synth pop', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('Thriller', 'Michael Jackson', ARRAY['pop', 'funk', 'horror', 'iconic'], 1983, 'bright', 'fast', '80s_top10'),
  ('Separate Ways (Worlds Apart)', 'Journey', ARRAY['arena rock', 'pop', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('Human Nature', 'Michael Jackson', ARRAY['pop', 'soft', 'romantic'], 1983, 'romantic', 'mid', '80s_top10'),
  ('Der Kommissar', 'After the Fire', ARRAY['new wave', 'synth pop', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('P.Y.T. (Pretty Young Thing)', 'Michael Jackson', ARRAY['pop', 'R&B', '1983s'], 1983, 'bright', 'mid', '80s_top10'),
  ('You and I', 'Eddie Rabbitt & Crystal Gayle', ARRAY['country pop', 'duet', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('Puttin'' On the Ritz', 'Taco', ARRAY['synth pop', 'novelty', 'retro'], 1983, 'playful', 'mid', '80s_top10'),
  ('Electric Avenue', 'Eddy Grant', ARRAY['reggae', 'pop', 'protest'], 1983, 'bright', 'mid', '80s_top10'),
  ('Uptown Girl', 'Billy Joel', ARRAY['pop', 'doo-wop', 'romantic', 'catchy'], 1983, 'romantic', 'mid', '80s_top10'),
  ('Stand Back', 'Stevie Nicks', ARRAY['rock', 'synth pop', 'powerful'], 1983, 'triumphant', 'mid', '80s_top10'),
  ('Our House', 'Madness', ARRAY['ska', 'new wave', 'British', 'nostalgic'], 1983, 'reflective', 'mid', '80s_top10'),
  ('1999', 'Prince', ARRAY['synth funk', 'dance', 'party', 'apocalyptic'], 1983, 'bright', 'fast', '80s_top10'),
  ('The Safety Dance', 'Men Without Hats', ARRAY['synth pop', 'new wave', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('One Thing Leads to Another', 'The Fixx', ARRAY['new wave', 'pop rock', 'pop'], 1983, 'bright', 'mid', '80s_top10'),
  ('When Doves Cry', 'Prince', ARRAY['pop', 'funk', 'experimental', 'iconic'], 1984, 'bright', 'fast', '80s_top10'),
  ('What''s Love Got to Do with It', 'Tina Turner', ARRAY['pop rock', 'pop', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Like a Virgin', 'Madonna', ARRAY['pop', 'dance pop', 'provocative'], 1984, 'bright', 'fast', '80s_top10'),
  ('Footloose', 'Kenny Loggins', ARRAY['pop rock', 'movie soundtrack', 'pop'], 1984, 'bright', 'mid', '80s_top10'),
  ('Against All Odds (Take a Look at Me Now)', 'Phil Collins', ARRAY['pop', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Ghostbusters', 'Ray Parker Jr.', ARRAY['pop', 'funk', 'movie soundtrack'], 1984, 'bright', 'fast', '80s_top10'),
  ('Jump', 'Van Halen', ARRAY['synth rock', 'arena rock', 'fun', 'iconic'], 1984, 'bright', 'fast', '80s_top10'),
  ('Let''s Go Crazy', 'Prince', ARRAY['rock', 'funk', 'party', 'energetic'], 1984, 'bright', 'fast', '80s_top10'),
  ('Owner of a Lonely Heart', 'Yes', ARRAY['progressive rock', 'synth rock', 'pop'], 1984, 'bright', 'mid', '80s_top10'),
  ('Hello', 'Lionel Richie', ARRAY['pop', 'ballad', 'romantic', 'smooth'], 1984, 'romantic', 'slow', '80s_top10'),
  ('Missing You', 'John Waite', ARRAY['pop rock', 'power ballad', 'pop'], 1984, 'romantic', 'slow', '80s_top10'),
  ('Let''s Hear It for the Boy', 'Deniece Williams', ARRAY['pop', 'R&B', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Karma Chameleon', 'Culture Club', ARRAY['pop', 'new wave', 'fun'], 1984, 'bright', 'fast', '80s_top10'),
  ('I Just Called to Say I Love You', 'Stevie Wonder', ARRAY['pop', 'R&B', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Out of Touch', 'Daryl Hall & John Oates', ARRAY['pop rock', 'synth pop', 'pop'], 1984, 'bright', 'mid', '80s_top10'),
  ('Wake Me Up Before You Go-Go', 'Wham!', ARRAY['pop', 'dance', 'fun'], 1984, 'bright', 'fast', '80s_top10'),
  ('Self Control', 'Laura Branigan', ARRAY['pop', 'synth pop', 'dark'], 1984, 'melancholy', 'mid', '80s_top10'),
  ('Dancing in the Dark', 'Bruce Springsteen', ARRAY['heartland rock', 'pop', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Time After Time', 'Cyndi Lauper', ARRAY['pop', 'ballad', 'romantic'], 1984, 'romantic', 'slow', '80s_top10'),
  ('Stuck on You', 'Lionel Richie', ARRAY['pop', 'country pop', 'romantic'], 1984, 'romantic', 'mid', '80s_top10'),
  ('Girls Just Want to Have Fun', 'Cyndi Lauper', ARRAY['pop', 'new wave', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Somebody''s Watching Me', 'Rockwell', ARRAY['pop', 'funk', 'paranoid'], 1984, 'bright', 'fast', '80s_top10'),
  ('The Reflex', 'Duran Duran', ARRAY['new wave', 'synth pop', 'dance'], 1984, 'bright', 'fast', '80s_top10'),
  ('Drive', 'The Cars', ARRAY['new wave', 'ballad', 'atmospheric'], 1984, 'romantic', 'slow', '80s_top10'),
  ('I Feel for You', 'Chaka Khan', ARRAY['R&B', 'funk', 'rap', 'dance'], 1984, 'bright', 'fast', '80s_top10'),
  ('Borderline', 'Madonna', ARRAY['pop', 'dance pop', 'catchy', 'synth'], 1984, 'bright', 'fast', '80s_top10'),
  ('Cover Me', 'Bruce Springsteen', ARRAY['rock', 'synth rock', 'dark'], 1984, 'melancholy', 'mid', '80s_top10'),
  ('Running with the Night', 'Lionel Richie', ARRAY['pop', 'R&B', '1984s'], 1984, 'bright', 'mid', '80s_top10'),
  ('Penny Lover', 'Lionel Richie', ARRAY['pop', 'R&B', 'romantic', 'smooth'], 1984, 'romantic', 'mid', '80s_top10'),
  ('Sister Christian', 'Night Ranger', ARRAY['arena rock', 'power ballad', 'pop'], 1984, 'romantic', 'slow', '80s_top10'),
  ('Sunglasses at Night', 'Corey Hart', ARRAY['synth pop', 'new wave', 'pop'], 1984, 'bright', 'mid', '80s_top10'),
  ('Legs', 'ZZ Top', ARRAY['blues rock', 'synth rock', 'fun', 'catchy'], 1984, 'bright', 'fast', '80s_top10'),
  ('I''m So Excited', 'Pointer Sisters', ARRAY['pop', 'R&B', 'dance'], 1984, 'bright', 'fast', '80s_top10'),
  ('Careless Whisper', 'Wham!', ARRAY['pop', 'ballad', 'saxophone'], 1985, 'romantic', 'slow', '80s_top10'),
  ('We Are the World', 'USA for Africa', ARRAY['pop', 'charity', 'anthem'], 1985, 'triumphant', 'mid', '80s_top10'),
  ('I Want to Know What Love Is', 'Foreigner', ARRAY['arena rock', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Can''t Fight This Feeling', 'REO Speedwagon', ARRAY['arena rock', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Everybody Wants to Rule the World', 'Tears for Fears', ARRAY['synth pop', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Money for Nothing', 'Dire Straits', ARRAY['rock', 'guitar', 'MTV anthem'], 1985, 'triumphant', 'mid', '80s_top10'),
  ('Take On Me', 'a-ha', ARRAY['synth pop', 'new wave', 'catchy', 'upbeat'], 1985, 'bright', 'fast', '80s_top10'),
  ('Saving All My Love for You', 'Whitney Houston', ARRAY['pop', 'R&B', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Say You, Say Me', 'Lionel Richie', ARRAY['pop', 'ballad', '1985s'], 1985, 'romantic', 'slow', '80s_top10'),
  ('Shout', 'Tears for Fears', ARRAY['synth pop', 'new wave', 'dramatic'], 1985, 'dramatic', 'mid', '80s_top10'),
  ('Part-Time Lover', 'Stevie Wonder', ARRAY['pop', 'synth', 'dance'], 1985, 'bright', 'fast', '80s_top10'),
  ('Separate Lives', 'Phil Collins & Marilyn Martin', ARRAY['pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Broken Wings', 'Mr. Mister', ARRAY['pop rock', 'synth pop', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('That''s What Friends Are For', 'Dionne & Friends', ARRAY['pop', 'charity', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Don''t You (Forget About Me)', 'Simple Minds', ARRAY['new wave', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('The Power of Love', 'Huey Lewis & The News', ARRAY['pop rock', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Cherish', 'Kool & The Gang', ARRAY['pop', 'R&B', 'romantic', 'smooth'], 1985, 'romantic', 'mid', '80s_top10'),
  ('One More Night', 'Phil Collins', ARRAY['pop', 'ballad', 'romantic'], 1985, 'romantic', 'slow', '80s_top10'),
  ('Sussudio', 'Phil Collins', ARRAY['pop', 'dance', 'synth', 'energetic'], 1985, 'bright', 'fast', '80s_top10'),
  ('Material Girl', 'Madonna', ARRAY['pop', 'dance', 'Marilyn Monroe'], 1985, 'bright', 'fast', '80s_top10'),
  ('Crazy for You', 'Madonna', ARRAY['pop', 'ballad', 'romantic'], 1985, 'romantic', 'slow', '80s_top10'),
  ('Heaven', 'Bryan Adams', ARRAY['pop rock', 'power ballad', 'romantic'], 1985, 'romantic', 'slow', '80s_top10'),
  ('Axel F', 'Harold Faltermeyer', ARRAY['synth', 'instrumental', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Raspberry Beret', 'Prince', ARRAY['pop', 'funk', 'psychedelic'], 1985, 'bright', 'fast', '80s_top10'),
  ('Relax', 'Frankie Goes to Hollywood', ARRAY['synth pop', 'dance', 'pop'], 1985, 'bright', 'fast', '80s_top10'),
  ('We Built This City', 'Starship', ARRAY['pop rock', 'arena rock', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Born in the U.S.A.', 'Bruce Springsteen', ARRAY['heartland rock', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('The Heat Is On', 'Glenn Frey', ARRAY['pop rock', 'movie soundtrack', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Walking on Sunshine', 'Katrina and the Waves', ARRAY['pop rock', 'fun', 'pop'], 1985, 'bright', 'fast', '80s_top10'),
  ('I''m on Fire', 'Bruce Springsteen', ARRAY['rock', 'minimalist', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Glory Days', 'Bruce Springsteen', ARRAY['heartland rock', 'fun', 'pop'], 1985, 'bright', 'fast', '80s_top10'),
  ('If You Love Somebody Set Them Free', 'Sting', ARRAY['pop rock', 'reggae', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Fortress Around Your Heart', 'Sting', ARRAY['pop rock', 'new wave', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('The Boys of Summer', 'Don Henley', ARRAY['pop rock', 'synth pop', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('Strut', 'Sheena Easton', ARRAY['pop', 'dance', 'synth', 'sultry'], 1985, 'romantic', 'fast', '80s_top10'),
  ('Smooth Operator', 'Sade', ARRAY['smooth jazz', 'pop', 'sophisticated'], 1985, 'romantic', 'mid', '80s_top10'),
  ('You Belong to the City', 'Glenn Frey', ARRAY['pop rock', 'synth', 'pop'], 1985, 'bright', 'mid', '80s_top10'),
  ('St. Elmo''s Fire (Man in Motion)', 'John Parr', ARRAY['pop rock', 'pop', '1985s'], 1985, 'bright', 'mid', '80s_top10'),
  ('Walk Like an Egyptian', 'The Bangles', ARRAY['pop rock', 'new wave', 'pop'], 1986, 'bright', 'mid', '80s_top10'),
  ('Papa Don''t Preach', 'Madonna', ARRAY['pop', 'dance', 'controversial'], 1986, 'bright', 'fast', '80s_top10'),
  ('Greatest Love of All', 'Whitney Houston', ARRAY['pop', 'inspirational', '1986s'], 1986, 'triumphant', 'mid', '80s_top10'),
  ('How Will I Know', 'Whitney Houston', ARRAY['pop', 'dance', 'synth'], 1986, 'bright', 'fast', '80s_top10'),
  ('Kiss', 'Prince', ARRAY['funk', 'minimal', 'falsetto', 'catchy'], 1986, 'bright', 'fast', '80s_top10'),
  ('Rock Me Amadeus', 'Falco', ARRAY['synth pop', 'rap', 'novelty'], 1986, 'playful', 'mid', '80s_top10'),
  ('Addicted to Love', 'Robert Palmer', ARRAY['pop rock', 'new wave', 'sexy'], 1986, 'bright', 'mid', '80s_top10'),
  ('Live to Tell', 'Madonna', ARRAY['pop', 'ballad', 'atmospheric'], 1986, 'romantic', 'slow', '80s_top10'),
  ('On My Own', 'Patti LaBelle & Michael McDonald', ARRAY['pop', 'R&B', '1986s'], 1986, 'bright', 'mid', '80s_top10'),
  ('Sledgehammer', 'Peter Gabriel', ARRAY['art rock', 'funk', 'innovative'], 1986, 'bright', 'fast', '80s_top10'),
  ('There''ll Be Sad Songs (To Make You Cry)', 'Billy Ocean', ARRAY['pop', '1986s'], 1986, 'bright', 'mid', '80s_top10'),
  ('Holding Back the Years', 'Simply Red', ARRAY['pop', 'soul', 'ballad'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Stuck with You', 'Huey Lewis & The News', ARRAY['pop rock', 'romantic', 'pop'], 1986, 'romantic', 'mid', '80s_top10'),
  ('Amanda', 'Boston', ARRAY['arena rock', 'power ballad', 'guitar', 'epic'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Burning Heart', 'Survivor', ARRAY['arena rock', 'movie soundtrack', 'pop'], 1986, 'bright', 'mid', '80s_top10'),
  ('West End Girls', 'Pet Shop Boys', ARRAY['synth pop', 'dance', 'urban'], 1986, 'bright', 'fast', '80s_top10'),
  ('Kyrie', 'Mr. Mister', ARRAY['pop rock', 'synth pop', 'dramatic'], 1986, 'dramatic', 'mid', '80s_top10'),
  ('Secret Lovers', 'Atlantic Starr', ARRAY['R&B', 'pop', 'romantic'], 1986, 'romantic', 'mid', '80s_top10'),
  ('Take My Breath Away', 'Berlin', ARRAY['synth pop', 'ballad', 'pop'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Sara', 'Starship', ARRAY['pop rock', 'power ballad', 'romantic'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Danger Zone', 'Kenny Loggins', ARRAY['pop rock', 'movie soundtrack', 'pop'], 1986, 'bright', 'mid', '80s_top10'),
  ('These Dreams', 'Heart', ARRAY['pop rock', 'dreamy', 'atmospheric'], 1986, 'dreamy', 'mid', '80s_top10'),
  ('Manic Monday', 'The Bangles', ARRAY['pop rock', 'new wave', 'pop'], 1986, 'bright', 'mid', '80s_top10'),
  ('Open Your Heart', 'Madonna', ARRAY['pop', 'dance', 'synth'], 1986, 'bright', 'fast', '80s_top10'),
  ('True Colors', 'Cyndi Lauper', ARRAY['pop', 'ballad', 'emotional'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Invisible Touch', 'Genesis', ARRAY['pop rock', 'synth pop', 'catchy'], 1986, 'bright', 'mid', '80s_top10'),
  ('Words Get in the Way', 'Miami Sound Machine', ARRAY['pop', 'ballad', '1986s'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Venus', 'Bananarama', ARRAY['pop', 'dance', 'fun', 'retro'], 1986, 'bright', 'fast', '80s_top10'),
  ('When I Think of You', 'Janet Jackson', ARRAY['pop', 'R&B', 'dance'], 1986, 'bright', 'fast', '80s_top10'),
  ('No One Is to Blame', 'Howard Jones', ARRAY['synth pop', 'ballad', 'pop'], 1986, 'romantic', 'slow', '80s_top10'),
  ('Your Love', 'The Outfield', ARRAY['pop rock', 'new wave', 'catchy'], 1986, 'bright', 'mid', '80s_top10'),
  ('Mad About You', 'Belinda Carlisle', ARRAY['pop', 'new wave', 'romantic'], 1986, 'romantic', 'mid', '80s_top10'),
  ('Life in a Northern Town', 'The Dream Academy', ARRAY['pop', 'new wave', '1986s'], 1986, 'bright', 'mid', '80s_top10'),
  ('If You Leave', 'OMD', ARRAY['synth pop', 'movie soundtrack', 'romantic'], 1986, 'romantic', 'mid', '80s_top10'),
  ('Take Me Home Tonight', 'Eddie Money', ARRAY['pop rock', 'arena rock', 'pop'], 1986, 'bright', 'mid', '80s_top10'),
  ('Livin'' on a Prayer', 'Bon Jovi', ARRAY['hair metal', 'arena rock', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('I Wanna Dance with Somebody', 'Whitney Houston', ARRAY['pop', 'dance', '1987s'], 1987, 'bright', 'fast', '80s_top10'),
  ('Alone', 'Heart', ARRAY['power ballad', 'arena rock', 'dramatic', 'diva'], 1987, 'romantic', 'slow', '80s_top10'),
  ('Nothing''s Gonna Stop Us Now', 'Starship', ARRAY['pop rock', 'pop', '1987s'], 1987, 'bright', 'mid', '80s_top10'),
  ('I Still Haven''t Found What I''m Looking For', 'U2', ARRAY['rock', 'pop', '1987s'], 1987, 'bright', 'mid', '80s_top10'),
  ('With or Without You', 'U2', ARRAY['rock', 'atmospheric', 'romantic'], 1987, 'romantic', 'mid', '80s_top10'),
  ('Here I Go Again', 'Whitesnake', ARRAY['hair metal', 'arena rock', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('Shake You Down', 'Gregory Abbott', ARRAY['R&B', 'pop', 'romantic'], 1987, 'romantic', 'mid', '80s_top10'),
  ('(I''ve Had) The Time of My Life', 'Bill Medley & Jennifer Warnes', ARRAY['pop', '1987s'], 1987, 'bright', 'mid', '80s_top10'),
  ('Faith', 'George Michael', ARRAY['pop rock', 'rockabilly', 'catchy'], 1987, 'bright', 'mid', '80s_top10'),
  ('La Bamba', 'Los Lobos', ARRAY['rock', 'Latin', 'movie soundtrack'], 1987, 'bright', 'mid', '80s_top10'),
  ('I Knew You Were Waiting (for Me)', 'Aretha Franklin & George Michael', ARRAY['pop', '1987s'], 1987, 'bright', 'mid', '80s_top10'),
  ('Lost in Emotion', 'Lisa Lisa & Cult Jam', ARRAY['pop', 'R&B', 'dance'], 1987, 'bright', 'fast', '80s_top10'),
  ('Head to Toe', 'Lisa Lisa & Cult Jam', ARRAY['pop', 'R&B', 'dance'], 1987, 'bright', 'fast', '80s_top10'),
  ('You Got It All', 'The Jets', ARRAY['pop', 'R&B', 'romantic', 'smooth'], 1987, 'romantic', 'mid', '80s_top10'),
  ('You Keep Me Hangin'' On', 'Kim Wilde', ARRAY['synth pop', 'dance', 'pop'], 1987, 'bright', 'fast', '80s_top10'),
  ('Lean on Me', 'Club Nouveau', ARRAY['pop', 'R&B', 'cover', 'uplifting'], 1987, 'bright', 'mid', '80s_top10'),
  ('Looking for a New Love', 'Jody Watley', ARRAY['pop', 'R&B', 'dance'], 1987, 'bright', 'fast', '80s_top10'),
  ('Heart and Soul', 'T''Pau', ARRAY['pop rock', 'synth pop', 'dramatic'], 1987, 'dramatic', 'mid', '80s_top10'),
  ('Wanted Dead or Alive', 'Bon Jovi', ARRAY['hard rock', 'arena rock', 'pop'], 1987, 'energetic', 'mid', '80s_top10'),
  ('U Got the Look', 'Prince', ARRAY['pop', 'funk', 'dance', 'duet'], 1987, 'bright', 'fast', '80s_top10'),
  ('Let''s Wait Awhile', 'Janet Jackson', ARRAY['R&B', 'pop', 'ballad'], 1987, 'romantic', 'slow', '80s_top10'),
  ('The Way It Is', 'Bruce Hornsby and the Range', ARRAY['pop rock', 'piano', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('Control', 'Janet Jackson', ARRAY['pop', 'R&B', 'dance', 'empowerment'], 1987, 'bright', 'fast', '80s_top10'),
  ('Notorious', 'Duran Duran', ARRAY['pop rock', 'funk', 'dance'], 1987, 'bright', 'fast', '80s_top10'),
  ('Tonight, Tonight, Tonight', 'Genesis', ARRAY['pop rock', 'synth pop', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('In Too Deep', 'Genesis', ARRAY['pop rock', 'soft rock', 'romantic'], 1987, 'romantic', 'mid', '80s_top10'),
  ('Land of Confusion', 'Genesis', ARRAY['pop rock', 'synth rock', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('Somewhere Out There', 'Linda Ronstadt & James Ingram', ARRAY['pop', '1987s'], 1987, 'bright', 'mid', '80s_top10'),
  ('Don''t Dream It''s Over', 'Crowded House', ARRAY['pop rock', 'alternative', 'pop'], 1987, 'bright', 'mid', '80s_top10'),
  ('Songbird', 'Kenny G', ARRAY['smooth jazz', 'instrumental', 'romantic'], 1987, 'romantic', 'mid', '80s_top10'),
  ('Point of No Return', 'Exposé', ARRAY['pop', 'dance', 'freestyle'], 1987, 'bright', 'fast', '80s_top10'),
  ('Is This Love', 'Whitesnake', ARRAY['hard rock', 'power ballad', 'pop'], 1987, 'romantic', 'slow', '80s_top10'),
  ('Hungry Eyes', 'Eric Carmen', ARRAY['pop', 'movie soundtrack', 'romantic'], 1987, 'romantic', 'mid', '80s_top10'),
  ('Need You Tonight', 'INXS', ARRAY['pop rock', 'funk', 'sexy', 'catchy'], 1988, 'bright', 'fast', '80s_top10'),
  ('Got My Mind Set on You', 'George Harrison', ARRAY['pop rock', 'retro', 'pop'], 1988, 'bright', 'mid', '80s_top10'),
  ('Never Gonna Give You Up', 'Rick Astley', ARRAY['pop', 'dance', 'synth'], 1988, 'bright', 'fast', '80s_top10'),
  ('Could''ve Been', 'Tiffany', ARRAY['pop', 'ballad', 'teen pop', 'romantic'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Seasons Change', 'Exposé', ARRAY['pop', 'ballad', 'freestyle'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Father Figure', 'George Michael', ARRAY['pop', 'R&B', 'romantic'], 1988, 'romantic', 'mid', '80s_top10'),
  ('Get Outta My Dreams, Get into My Car', 'Billy Ocean', ARRAY['pop', 'R&B', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Where Do Broken Hearts Go', 'Whitney Houston', ARRAY['pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Anything for You', 'Gloria Estefan & Miami Sound Machine', ARRAY['pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('One More Try', 'George Michael', ARRAY['pop', 'soul', 'ballad'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Together Forever', 'Rick Astley', ARRAY['pop', 'dance', 'synth'], 1988, 'bright', 'fast', '80s_top10'),
  ('Dirty Diana', 'Michael Jackson', ARRAY['pop', 'rock', 'dark', 'guitar'], 1988, 'melancholy', 'mid', '80s_top10'),
  ('Roll with It', 'Steve Winwood', ARRAY['pop rock', 'blue-eyed soul', 'pop'], 1988, 'bright', 'mid', '80s_top10'),
  ('Monkey', 'George Michael', ARRAY['pop', 'funk', 'dance', 'catchy'], 1988, 'bright', 'fast', '80s_top10'),
  ('Sweet Child O'' Mine', 'Guns N'' Roses', ARRAY['hard rock', 'guitar solo', 'pop'], 1988, 'energetic', 'mid', '80s_top10'),
  ('Don''t Worry Be Happy', 'Bobby McFerrin', ARRAY['pop', 'a cappella', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Look Away', 'Chicago', ARRAY['pop rock', 'ballad', 'heartbreak'], 1988, 'melancholy', 'slow', '80s_top10'),
  ('Red Red Wine', 'UB40', ARRAY['reggae', 'pop', 'cover', 'mellow'], 1988, 'dreamy', 'slow', '80s_top10'),
  ('Wild, Wild West', 'The Escape Club', ARRAY['pop rock', 'catchy', 'fun'], 1988, 'bright', 'fast', '80s_top10'),
  ('Baby, I Love Your Way/Freebird Medley', 'Will to Power', ARRAY['pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Every Rose Has Its Thorn', 'Poison', ARRAY['hair metal', 'power ballad', 'pop'], 1988, 'romantic', 'slow', '80s_top10'),
  ('I Think We''re Alone Now', 'Tiffany', ARRAY['pop', 'teen pop', 'cover'], 1988, 'bright', 'mid', '80s_top10'),
  ('Man in the Mirror', 'Michael Jackson', ARRAY['pop', 'gospel', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Hazy Shade of Winter', 'Bangles', ARRAY['pop rock', 'cover', 'energetic'], 1988, 'energetic', 'fast', '80s_top10'),
  ('What Have I Done to Deserve This?', 'Pet Shop Boys & Dusty Springfield', ARRAY['pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('I Don''t Want to Live Without You', 'Foreigner', ARRAY['arena rock', 'pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('Hysteria', 'Def Leppard', ARRAY['hard rock', 'hair metal', 'atmospheric'], 1988, 'energetic', 'mid', '80s_top10'),
  ('The Flame', 'Cheap Trick', ARRAY['pop rock', 'power ballad', 'romantic'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Pour Some Sugar on Me', 'Def Leppard', ARRAY['hard rock', 'hair metal', 'pop'], 1988, 'energetic', 'mid', '80s_top10'),
  ('Simply Irresistible', 'Robert Palmer', ARRAY['pop rock', 'new wave', 'pop'], 1988, 'bright', 'mid', '80s_top10'),
  ('Foolish Beat', 'Debbie Gibson', ARRAY['pop', 'teen pop', 'ballad'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Make Me Lose Control', 'Eric Carmen', ARRAY['pop rock', 'nostalgic', 'pop'], 1988, 'reflective', 'mid', '80s_top10'),
  ('The Way You Make Me Feel', 'Michael Jackson', ARRAY['pop', 'dance', '1988s'], 1988, 'bright', 'fast', '80s_top10'),
  ('I Hate Myself for Loving You', 'Joan Jett & The Blackhearts', ARRAY['pop', '1988s'], 1988, 'bright', 'mid', '80s_top10'),
  ('What a Wonderful World', 'Louis Armstrong', ARRAY['jazz', 'standard', 'pop'], 1988, 'bright', 'mid', '80s_top10'),
  ('Naughty Girls (Need Love Too)', 'Samantha Fox', ARRAY['pop', 'dance', '1988s'], 1988, 'bright', 'fast', '80s_top10'),
  ('Sign Your Name', 'Terence Trent D''Arby', ARRAY['R&B', 'pop', 'soulful'], 1988, 'bright', 'mid', '80s_top10'),
  ('Hands to Heaven', 'Breathe', ARRAY['pop', 'soft rock', 'romantic'], 1988, 'romantic', 'mid', '80s_top10'),
  ('Love Bites', 'Def Leppard', ARRAY['hard rock', 'power ballad', 'pop'], 1988, 'romantic', 'slow', '80s_top10'),
  ('Bad Medicine', 'Bon Jovi', ARRAY['hard rock', 'arena rock', 'catchy'], 1988, 'bright', 'mid', '80s_top10'),
  ('New Sensation', 'INXS', ARRAY['pop rock', 'dance rock', 'catchy'], 1988, 'bright', 'fast', '80s_top10'),
  ('Never Tear Us Apart', 'INXS', ARRAY['pop rock', 'dramatic', 'romantic'], 1988, 'romantic', 'mid', '80s_top10'),
  ('Straight Up', 'Paula Abdul', ARRAY['pop', 'dance', 'synth', 'catchy'], 1989, 'bright', 'fast', '80s_top10'),
  ('Lost in Your Eyes', 'Debbie Gibson', ARRAY['pop', 'teen pop', 'ballad'], 1989, 'romantic', 'slow', '80s_top10'),
  ('The Living Years', 'Mike + The Mechanics', ARRAY['pop rock', 'ballad', 'pop'], 1989, 'romantic', 'slow', '80s_top10'),
  ('She Drives Me Crazy', 'Fine Young Cannibals', ARRAY['pop rock', 'funk', 'pop'], 1989, 'bright', 'fast', '80s_top10'),
  ('Like a Prayer', 'Madonna', ARRAY['pop', 'dance', 'gospel'], 1989, 'bright', 'fast', '80s_top10'),
  ('Forever Your Girl', 'Paula Abdul', ARRAY['pop', 'dance', 'synth'], 1989, 'bright', 'fast', '80s_top10'),
  ('Rock On', 'Michael Damian', ARRAY['pop rock', 'cover', 'retro', 'catchy'], 1989, 'bright', 'mid', '80s_top10'),
  ('Wind Beneath My Wings', 'Bette Midler', ARRAY['pop', 'power ballad', '1989s'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Satisfied', 'Richard Marx', ARRAY['pop rock', 'catchy', 'romantic'], 1989, 'romantic', 'mid', '80s_top10'),
  ('Batdance', 'Prince', ARRAY['pop', 'funk', 'movie soundtrack'], 1989, 'bright', 'fast', '80s_top10'),
  ('Right Here Waiting', 'Richard Marx', ARRAY['pop', 'power ballad', '1989s'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Cold Hearted', 'Paula Abdul', ARRAY['pop', 'dance', 'synth'], 1989, 'bright', 'fast', '80s_top10'),
  ('Miss You Much', 'Janet Jackson', ARRAY['pop', 'R&B', 'dance', 'catchy'], 1989, 'bright', 'fast', '80s_top10'),
  ('Listen to Your Heart', 'Roxette', ARRAY['pop rock', 'power ballad', 'pop'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Blame It on the Rain', 'Milli Vanilli', ARRAY['pop', 'dance', 'synth'], 1989, 'bright', 'fast', '80s_top10'),
  ('We Didn''t Start the Fire', 'Billy Joel', ARRAY['pop rock', 'pop', '1989s'], 1989, 'bright', 'mid', '80s_top10'),
  ('Another Day in Paradise', 'Phil Collins', ARRAY['pop', '1989s'], 1989, 'bright', 'mid', '80s_top10'),
  ('When I See You Smile', 'Bad English', ARRAY['arena rock', 'power ballad', 'pop'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Eternal Flame', 'The Bangles', ARRAY['pop rock', 'ballad', 'romantic'], 1989, 'romantic', 'slow', '80s_top10'),
  ('The Look', 'Roxette', ARRAY['pop rock', 'catchy', 'Swedish', 'fun'], 1989, 'bright', 'fast', '80s_top10'),
  ('Express Yourself', 'Madonna', ARRAY['pop', 'dance', 'empowerment'], 1989, 'bright', 'fast', '80s_top10'),
  ('Don''t Wanna Lose You', 'Gloria Estefan', ARRAY['pop', 'ballad', '1989s'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Good Thing', 'Fine Young Cannibals', ARRAY['pop rock', 'funk', 'dance'], 1989, 'bright', 'fast', '80s_top10'),
  ('Girl You Know It''s True', 'Milli Vanilli', ARRAY['pop', 'dance', 'synth'], 1989, 'bright', 'fast', '80s_top10'),
  ('If I Could Turn Back Time', 'Cher', ARRAY['pop rock', 'power ballad', 'pop'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Bust a Move', 'Young MC', ARRAY['hip hop', 'rap', 'fun', 'party'], 1989, 'bright', 'fast', '80s_top10'),
  ('My Prerogative', 'Bobby Brown', ARRAY['R&B', 'new jack swing', 'dance'], 1989, 'bright', 'fast', '80s_top10'),
  ('Don''t Rush Me', 'Taylor Dayne', ARRAY['pop', 'dance', 'powerful'], 1989, 'bright', 'fast', '80s_top10'),
  ('Armageddon It', 'Def Leppard', ARRAY['hard rock', 'hair metal', 'catchy'], 1989, 'bright', 'mid', '80s_top10'),
  ('Patience', 'Guns N'' Roses', ARRAY['hard rock', 'ballad', 'acoustic'], 1989, 'romantic', 'slow', '80s_top10'),
  ('Stand', 'R.E.M.', ARRAY['alternative', 'pop rock', 'quirky', 'catchy'], 1989, 'bright', 'mid', '80s_top10'),
  ('Love Shack', 'The B-52''s', ARRAY['pop rock', 'new wave', 'fun', 'party'], 1989, 'bright', 'fast', '80s_top10'),
  ('Giving You the Best That I Got', 'Anita Baker', ARRAY['R&B', 'jazz', 'pop'], 1989, 'bright', 'mid', '80s_top10'),
  ('What I Am', 'Edie Brickell & New Bohemians', ARRAY['alternative', 'pop', '1989s'], 1989, 'bright', 'mid', '80s_top10'),
  ('Angel of Harlem', 'U2', ARRAY['rock', 'soul', 'tribute', 'upbeat'], 1989, 'bright', 'fast', '80s_top10'),
  ('Don''t Know What You Got (Till It''s Gone)', 'Cinderella', ARRAY['pop', '1989s'], 1989, 'bright', 'mid', '80s_top10'),
  ('I''ll Be There for You', 'Bon Jovi', ARRAY['hard rock', 'arena rock', 'pop'], 1989, 'energetic', 'mid', '80s_top10'),
  ('Toy Soldiers', 'Martika', ARRAY['pop', 'dramatic', 'addiction theme'], 1989, 'dramatic', 'mid', '80s_top10'),
  ('Cherish', 'Madonna', ARRAY['pop', 'dance', 'romantic', 'fun'], 1989, 'romantic', 'fast', '80s_top10'),
  ('Roam', 'The B-52''s', ARRAY['pop rock', 'new wave', 'fun', 'travel'], 1989, 'bright', 'fast', '80s_top10');