-- 2000s Hits seed data
INSERT INTO songs (title, artist, category, year, mood, tempo, tags) VALUES

-- 2000
('Breathe', 'Faith Hill', '2000s_hits', 2000, 'romantic', 'slow', ARRAY['country pop', 'ballad', 'crossover']),
('Beautiful Day', 'U2', '2000s_hits', 2000, 'uplifting', 'mid', ARRAY['rock', 'alternative', 'anthem']),
('Bent', 'Matchbox Twenty', '2000s_hits', 2000, 'melancholy', 'mid', ARRAY['pop rock', 'alternative']),
('The Real Slim Shady', 'Eminem', '2000s_hits', 2000, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'comedy']),
('Stan', 'Eminem', '2000s_hits', 2000, 'intense', 'mid', ARRAY['hip hop', 'rap', 'dark']),
('Incomplete', 'Sisqo', '2000s_hits', 2000, 'romantic', 'slow', ARRAY['R&B', 'ballad']),
('Thong Song', 'Sisqo', '2000s_hits', 2000, 'fun', 'fast', ARRAY['R&B', 'dance']),
('Say My Name', 'Destiny''s Child', '2000s_hits', 2000, 'energetic', 'mid', ARRAY['R&B', 'pop', 'girl group']),
('Independent Women Part I', 'Destiny''s Child', '2000s_hits', 2000, 'empowering', 'mid', ARRAY['R&B', 'pop', 'girl group']),
('Oops!... I Did It Again', 'Britney Spears', '2000s_hits', 2000, 'flirty', 'mid', ARRAY['pop', 'dance pop']),
('Lucky', 'Britney Spears', '2000s_hits', 2000, 'bittersweet', 'mid', ARRAY['pop', 'dance pop']),
('Try Again', 'Aaliyah', '2000s_hits', 2000, 'smooth', 'mid', ARRAY['R&B', 'dance', 'hip hop']),
('Who Let the Dogs Out', 'Baha Men', '2000s_hits', 2000, 'fun', 'fast', ARRAY['pop', 'dance', 'novelty']),
('Kryptonite', '3 Doors Down', '2000s_hits', 2000, 'intense', 'mid', ARRAY['rock', 'post-grunge', 'alternative']),
('Bye Bye Bye', 'NSYNC', '2000s_hits', 2000, 'energetic', 'fast', ARRAY['pop', 'boy band', 'dance pop']),
('It''s Gonna Be Me', 'NSYNC', '2000s_hits', 2000, 'upbeat', 'mid', ARRAY['pop', 'boy band', 'dance pop']),
('Maria Maria', 'Santana', '2000s_hits', 2000, 'smooth', 'mid', ARRAY['latin', 'rock', 'R&B']),
('I Try', 'Macy Gray', '2000s_hits', 2000, 'bittersweet', 'mid', ARRAY['R&B', 'soul', 'pop']),

-- 2001
('Hanging by a Moment', 'Lifehouse', '2000s_hits', 2001, 'romantic', 'mid', ARRAY['pop rock', 'alternative', 'ballad']),
('Fallin''', 'Alicia Keys', '2000s_hits', 2001, 'soulful', 'slow', ARRAY['R&B', 'soul', 'piano']),
('Drops of Jupiter', 'Train', '2000s_hits', 2001, 'uplifting', 'mid', ARRAY['pop rock', 'alternative']),
('Jaded', 'Aerosmith', '2000s_hits', 2001, 'melancholy', 'mid', ARRAY['rock', 'pop rock', 'ballad']),
('All for You', 'Janet Jackson', '2000s_hits', 2001, 'upbeat', 'fast', ARRAY['R&B', 'pop', 'dance']),
('Loverboy', 'Mariah Carey', '2000s_hits', 2001, 'upbeat', 'fast', ARRAY['pop', 'R&B', 'dance']),
('Stutter', 'Joe', '2000s_hits', 2001, 'smooth', 'mid', ARRAY['R&B', 'pop']),
('U Remind Me', 'Usher', '2000s_hits', 2001, 'smooth', 'mid', ARRAY['R&B', 'pop']),
('Get Ur Freak On', 'Missy Elliott', '2000s_hits', 2001, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'dance']),
('Bootylicious', 'Destiny''s Child', '2000s_hits', 2001, 'energetic', 'fast', ARRAY['R&B', 'pop', 'girl group']),
('Survivor', 'Destiny''s Child', '2000s_hits', 2001, 'empowering', 'fast', ARRAY['R&B', 'pop', 'girl group']),
('Ride Wit Me', 'Nelly', '2000s_hits', 2001, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'R&B']),
('In the End', 'Linkin Park', '2000s_hits', 2001, 'intense', 'mid', ARRAY['rock', 'nu-metal', 'alternative']),
('Crawling', 'Linkin Park', '2000s_hits', 2001, 'intense', 'mid', ARRAY['rock', 'nu-metal', 'alternative']),
('Clint Eastwood', 'Gorillaz', '2000s_hits', 2001, 'dark', 'mid', ARRAY['alternative', 'hip hop', 'art rock']),
('Again', 'Lenny Kravitz', '2000s_hits', 2001, 'romantic', 'slow', ARRAY['rock', 'R&B', 'soul']),
('Heard It All Before', 'Sunshine Anderson', '2000s_hits', 2001, 'soulful', 'mid', ARRAY['R&B', 'soul']),
('Lifestyles of the Rich and Famous', 'Good Charlotte', '2000s_hits', 2001, 'energetic', 'fast', ARRAY['pop punk', 'punk', 'rock']),

-- 2002
('Complicated', 'Avril Lavigne', '2000s_hits', 2002, 'angsty', 'mid', ARRAY['pop punk', 'pop rock', 'teen pop']),
('Sk8er Boi', 'Avril Lavigne', '2000s_hits', 2002, 'energetic', 'fast', ARRAY['pop punk', 'pop rock', 'teen pop']),
('A Thousand Miles', 'Vanessa Carlton', '2000s_hits', 2002, 'romantic', 'mid', ARRAY['pop', 'piano pop', 'soft rock']),
('Don''t Know Why', 'Norah Jones', '2000s_hits', 2002, 'mellow', 'slow', ARRAY['jazz pop', 'soft rock', 'adult contemporary']),
('How You Remind Me', 'Nickelback', '2000s_hits', 2002, 'intense', 'mid', ARRAY['rock', 'post-grunge', 'alternative']),
('Blurry', 'Puddle of Mudd', '2000s_hits', 2002, 'melancholy', 'mid', ARRAY['rock', 'post-grunge', 'alternative']),
('Hero', 'Enrique Iglesias', '2000s_hits', 2002, 'romantic', 'slow', ARRAY['pop', 'latin pop', 'ballad']),
('Whenever, Wherever', 'Shakira', '2000s_hits', 2002, 'upbeat', 'fast', ARRAY['latin pop', 'dance pop', 'pop']),
('Foolish', 'Ashanti', '2000s_hits', 2002, 'smooth', 'slow', ARRAY['R&B', 'hip hop soul']),
('Always on Time', 'Ja Rule', '2000s_hits', 2002, 'smooth', 'mid', ARRAY['hip hop', 'R&B', 'rap']),
('Dilemma', 'Nelly', '2000s_hits', 2002, 'smooth', 'mid', ARRAY['hip hop', 'R&B', 'rap']),
('Hot in Herre', 'Nelly', '2000s_hits', 2002, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'dance']),
('Without Me', 'Eminem', '2000s_hits', 2002, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'comedy']),
('Lose Yourself', 'Eminem', '2000s_hits', 2002, 'intense', 'fast', ARRAY['hip hop', 'rap', 'anthem']),
('Work It', 'Missy Elliott', '2000s_hits', 2002, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'dance']),
('Landslide', 'Fleetwood Mac', '2000s_hits', 2002, 'melancholy', 'slow', ARRAY['rock', 'soft rock', 'classic']),
('The Middle', 'Jimmy Eat World', '2000s_hits', 2002, 'uplifting', 'fast', ARRAY['pop rock', 'alternative', 'emo']),
('In My Place', 'Coldplay', '2000s_hits', 2002, 'melancholy', 'mid', ARRAY['alternative rock', 'post-Britpop']),

-- 2003
('Crazy in Love', 'Beyoncé', '2000s_hits', 2003, 'energetic', 'fast', ARRAY['R&B', 'pop', 'dance']),
('Baby Boy', 'Beyoncé', '2000s_hits', 2003, 'smooth', 'mid', ARRAY['R&B', 'dancehall', 'pop']),
('Ignition (Remix)', 'R. Kelly', '2000s_hits', 2003, 'smooth', 'mid', ARRAY['R&B', 'hip hop soul']),
('In Da Club', '50 Cent', '2000s_hits', 2003, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'party']),
('P.I.M.P.', '50 Cent', '2000s_hits', 2003, 'smooth', 'mid', ARRAY['hip hop', 'rap']),
('Bring Me to Life', 'Evanescence', '2000s_hits', 2003, 'intense', 'mid', ARRAY['rock', 'alternative metal', 'gothic rock']),
('Somewhere I Belong', 'Linkin Park', '2000s_hits', 2003, 'intense', 'mid', ARRAY['rock', 'nu-metal', 'alternative']),
('Stacy''s Mom', 'Fountains of Wayne', '2000s_hits', 2003, 'fun', 'fast', ARRAY['pop rock', 'power pop', 'alternative']),
('Unwell', 'Matchbox Twenty', '2000s_hits', 2003, 'melancholy', 'mid', ARRAY['pop rock', 'alternative']),
('Beautiful', 'Christina Aguilera', '2000s_hits', 2003, 'uplifting', 'slow', ARRAY['pop', 'ballad', 'empowering']),
('Fighter', 'Christina Aguilera', '2000s_hits', 2003, 'empowering', 'mid', ARRAY['pop', 'dance pop']),
('Cry Me a River', 'Justin Timberlake', '2000s_hits', 2003, 'melancholy', 'mid', ARRAY['R&B', 'pop', 'neo soul']),
('Rock Your Body', 'Justin Timberlake', '2000s_hits', 2003, 'upbeat', 'fast', ARRAY['R&B', 'pop', 'dance']),
('Milkshake', 'Kelis', '2000s_hits', 2003, 'fun', 'mid', ARRAY['R&B', 'electronica', 'dance']),
('Right Thurr', 'Chingy', '2000s_hits', 2003, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'R&B']),
('Testify', 'Rage Against the Machine', '2000s_hits', 2003, 'intense', 'fast', ARRAY['rock', 'rap rock', 'alternative']),
('Seven Nation Army', 'The White Stripes', '2000s_hits', 2003, 'intense', 'mid', ARRAY['rock', 'garage rock', 'alternative']),
('Are You Gonna Be My Girl', 'Jet', '2000s_hits', 2003, 'energetic', 'fast', ARRAY['rock', 'garage rock', 'alternative']),
('Waiting for Tonight', 'Jennifer Lopez', '2000s_hits', 2003, 'upbeat', 'fast', ARRAY['pop', 'dance pop', 'latin pop']),

-- 2004
('Yeah!', 'Usher', '2000s_hits', 2004, 'energetic', 'fast', ARRAY['R&B', 'crunk', 'dance pop']),
('Burn', 'Usher', '2000s_hits', 2004, 'smooth', 'mid', ARRAY['R&B', 'pop', 'ballad']),
('Confessions Part II', 'Usher', '2000s_hits', 2004, 'smooth', 'mid', ARRAY['R&B', 'pop']),
('My Boo', 'Usher', '2000s_hits', 2004, 'romantic', 'slow', ARRAY['R&B', 'pop']),
('Numb', 'Linkin Park', '2000s_hits', 2004, 'intense', 'mid', ARRAY['rock', 'nu-metal', 'alternative']),
('The Reason', 'Hoobastank', '2000s_hits', 2004, 'melancholy', 'mid', ARRAY['rock', 'post-grunge', 'alternative']),
('This Love', 'Maroon 5', '2000s_hits', 2004, 'upbeat', 'fast', ARRAY['pop rock', 'funk rock', 'alternative']),
('She Will Be Loved', 'Maroon 5', '2000s_hits', 2004, 'romantic', 'mid', ARRAY['pop rock', 'soft rock']),
('Hey Ya!', 'OutKast', '2000s_hits', 2004, 'fun', 'fast', ARRAY['hip hop', 'funk', 'alternative']),
('The Way You Move', 'OutKast', '2000s_hits', 2004, 'upbeat', 'fast', ARRAY['hip hop', 'funk', 'R&B']),
('Slow Motion', 'Trey Songz', '2000s_hits', 2004, 'smooth', 'slow', ARRAY['R&B', 'hip hop soul']),
('Lean Back', 'Terror Squad', '2000s_hits', 2004, 'energetic', 'fast', ARRAY['hip hop', 'rap']),
('Drop It Like It''s Hot', 'Snoop Dogg', '2000s_hits', 2004, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'West Coast']),
('Goodies', 'Ciara', '2000s_hits', 2004, 'smooth', 'mid', ARRAY['R&B', 'crunk', 'dance pop']),
('1, 2 Step', 'Ciara', '2000s_hits', 2004, 'energetic', 'fast', ARRAY['R&B', 'dance pop']),
('Toxic', 'Britney Spears', '2000s_hits', 2004, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Everytime', 'Britney Spears', '2000s_hits', 2004, 'melancholy', 'slow', ARRAY['pop', 'ballad']),
('Jesus Walks', 'Kanye West', '2000s_hits', 2004, 'intense', 'mid', ARRAY['hip hop', 'rap', 'gospel']),
('Through the Wire', 'Kanye West', '2000s_hits', 2004, 'intense', 'mid', ARRAY['hip hop', 'rap']),
('Take My Breath Away', 'Mario Winans', '2000s_hits', 2004, 'smooth', 'slow', ARRAY['R&B', 'hip hop soul']),

-- 2005
('Gold Digger', 'Kanye West', '2000s_hits', 2005, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'soul sample']),
('Diamonds from Sierra Leone', 'Kanye West', '2000s_hits', 2005, 'intense', 'mid', ARRAY['hip hop', 'rap']),
('Hollaback Girl', 'Gwen Stefani', '2000s_hits', 2005, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'hip hop pop']),
('Cool', 'Gwen Stefani', '2000s_hits', 2005, 'upbeat', 'mid', ARRAY['pop', 'new wave pop']),
('Since U Been Gone', 'Kelly Clarkson', '2000s_hits', 2005, 'empowering', 'fast', ARRAY['pop rock', 'pop']),
('Behind These Hazel Eyes', 'Kelly Clarkson', '2000s_hits', 2005, 'intense', 'mid', ARRAY['pop rock', 'pop']),
('We Belong Together', 'Mariah Carey', '2000s_hits', 2005, 'romantic', 'slow', ARRAY['R&B', 'pop', 'ballad']),
('Shake It Off', 'Mariah Carey', '2000s_hits', 2005, 'upbeat', 'fast', ARRAY['R&B', 'pop', 'dance']),
('1 Thing', 'Amerie', '2000s_hits', 2005, 'upbeat', 'fast', ARRAY['R&B', 'funk']),
('Don''t Cha', 'Pussycat Dolls', '2000s_hits', 2005, 'energetic', 'fast', ARRAY['pop', 'R&B', 'dance pop']),
('Buttons', 'Pussycat Dolls', '2000s_hits', 2005, 'smooth', 'mid', ARRAY['pop', 'R&B', 'dance pop']),
('Pon de Replay', 'Rihanna', '2000s_hits', 2005, 'upbeat', 'fast', ARRAY['pop', 'dancehall', 'R&B']),
('SOS', 'Rihanna', '2000s_hits', 2005, 'upbeat', 'fast', ARRAY['pop', 'dance pop', 'R&B']),
('Feel Good Inc.', 'Gorillaz', '2000s_hits', 2005, 'dark', 'mid', ARRAY['alternative', 'hip hop', 'art rock']),
('Speed of Sound', 'Coldplay', '2000s_hits', 2005, 'uplifting', 'mid', ARRAY['alternative rock', 'post-Britpop']),
('Boulevard of Broken Dreams', 'Green Day', '2000s_hits', 2005, 'melancholy', 'mid', ARRAY['punk rock', 'alternative', 'rock']),
('Wake Me Up When September Ends', 'Green Day', '2000s_hits', 2005, 'melancholy', 'mid', ARRAY['punk rock', 'alternative', 'rock']),
('Mr. Brightside', 'The Killers', '2000s_hits', 2005, 'intense', 'fast', ARRAY['indie rock', 'alternative', 'new wave revival']),
('Somebody Told Me', 'The Killers', '2000s_hits', 2005, 'energetic', 'fast', ARRAY['indie rock', 'alternative', 'new wave revival']),
('Sugar We''re Goin Down', 'Fall Out Boy', '2000s_hits', 2005, 'energetic', 'fast', ARRAY['pop punk', 'emo', 'alternative']),

-- 2006
('Irreplaceable', 'Beyoncé', '2000s_hits', 2006, 'empowering', 'mid', ARRAY['R&B', 'pop', 'country soul']),
('Déjà Vu', 'Beyoncé', '2000s_hits', 2006, 'energetic', 'fast', ARRAY['R&B', 'funk', 'pop']),
('Hips Don''t Lie', 'Shakira', '2000s_hits', 2006, 'upbeat', 'fast', ARRAY['latin pop', 'dance pop', 'pop']),
('Unfaithful', 'Rihanna', '2000s_hits', 2006, 'melancholy', 'slow', ARRAY['pop', 'R&B', 'ballad']),
('Promiscuous', 'Nelly Furtado', '2000s_hits', 2006, 'upbeat', 'fast', ARRAY['pop', 'R&B', 'dance pop']),
('Maneater', 'Nelly Furtado', '2000s_hits', 2006, 'smooth', 'mid', ARRAY['pop', 'R&B', 'dance pop']),
('SexyBack', 'Justin Timberlake', '2000s_hits', 2006, 'smooth', 'mid', ARRAY['pop', 'R&B', 'electropop']),
('My Love', 'Justin Timberlake', '2000s_hits', 2006, 'smooth', 'mid', ARRAY['R&B', 'pop', 'electropop']),
('Temperature', 'Sean Paul', '2000s_hits', 2006, 'upbeat', 'fast', ARRAY['dancehall', 'reggae pop', 'pop']),
('Crazy', 'Gnarls Barkley', '2000s_hits', 2006, 'melancholy', 'mid', ARRAY['soul', 'alternative R&B', 'psychedelic soul']),
('Check on It', 'Beyoncé', '2000s_hits', 2006, 'energetic', 'fast', ARRAY['R&B', 'hip hop soul', 'dance']),
('Ridin''', 'Chamillionaire', '2000s_hits', 2006, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'Southern rap']),
('Grillz', 'Nelly', '2000s_hits', 2006, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'crunk']),
('The Sweet Escape', 'Gwen Stefani', '2000s_hits', 2006, 'upbeat', 'fast', ARRAY['pop', 'dance pop']),
('When You''re Gone', 'Avril Lavigne', '2000s_hits', 2006, 'melancholy', 'mid', ARRAY['pop rock', 'pop', 'ballad']),
('Chasing Cars', 'Snow Patrol', '2000s_hits', 2006, 'melancholy', 'slow', ARRAY['alternative rock', 'indie rock', 'post-rock']),
('Welcome to the Black Parade', 'My Chemical Romance', '2000s_hits', 2006, 'intense', 'fast', ARRAY['emo', 'pop punk', 'theatrical rock']),
('Far Away', 'Nickelback', '2000s_hits', 2006, 'romantic', 'slow', ARRAY['rock', 'post-grunge', 'ballad']),

-- 2007
('Umbrella', 'Rihanna', '2000s_hits', 2007, 'smooth', 'mid', ARRAY['pop', 'R&B', 'dance pop']),
('Good Girl Gone Bad', 'Rihanna', '2000s_hits', 2007, 'energetic', 'fast', ARRAY['pop', 'R&B', 'dance pop']),
('Stronger', 'Kanye West', '2000s_hits', 2007, 'intense', 'fast', ARRAY['hip hop', 'rap', 'electronic']),
('Bartender', 'T-Pain', '2000s_hits', 2007, 'smooth', 'mid', ARRAY['R&B', 'hip hop', 'crunk']),
('Low', 'Flo Rida', '2000s_hits', 2007, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'crunk']),
('Beautiful Girls', 'Sean Kingston', '2000s_hits', 2007, 'bittersweet', 'mid', ARRAY['reggae pop', 'pop', 'dancehall']),
('No One', 'Alicia Keys', '2000s_hits', 2007, 'romantic', 'mid', ARRAY['R&B', 'soul', 'pop']),
('Like a Boy', 'Ciara', '2000s_hits', 2007, 'smooth', 'mid', ARRAY['R&B', 'hip hop soul']),
('Party Like a Rockstar', 'Shop Boyz', '2000s_hits', 2007, 'energetic', 'fast', ARRAY['hip hop', 'rap', 'crunk']),
('Big Girls Don''t Cry', 'Fergie', '2000s_hits', 2007, 'bittersweet', 'mid', ARRAY['pop', 'R&B']),
('Glamorous', 'Fergie', '2000s_hits', 2007, 'upbeat', 'fast', ARRAY['pop', 'hip hop pop', 'R&B']),
('Apologize', 'Timbaland', '2000s_hits', 2007, 'melancholy', 'mid', ARRAY['pop', 'R&B', 'ballad']),
('The Way I Are', 'Timbaland', '2000s_hits', 2007, 'smooth', 'mid', ARRAY['R&B', 'hip hop', 'dance pop']),
('Gives You Hell', 'The All-American Rejects', '2000s_hits', 2007, 'angsty', 'fast', ARRAY['pop rock', 'alternative', 'pop punk']),
('Paralyzer', 'Finger Eleven', '2000s_hits', 2007, 'intense', 'fast', ARRAY['rock', 'alternative', 'post-grunge']),
('Grace Kelly', 'MIKA', '2000s_hits', 2007, 'fun', 'fast', ARRAY['pop', 'glam pop', 'alternative']),
('Smile', 'Lily Allen', '2000s_hits', 2007, 'upbeat', 'fast', ARRAY['pop', 'ska pop', 'indie pop']),
('Rehab', 'Amy Winehouse', '2000s_hits', 2007, 'soulful', 'fast', ARRAY['soul', 'R&B', 'jazz']),
('Valerie', 'Amy Winehouse', '2000s_hits', 2007, 'upbeat', 'fast', ARRAY['soul', 'R&B', 'Motown revival']),

-- 2008
('Single Ladies (Put a Ring on It)', 'Beyoncé', '2000s_hits', 2008, 'empowering', 'fast', ARRAY['R&B', 'pop', 'dance']),
('Lollipop', 'Lil Wayne', '2000s_hits', 2008, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'crunk']),
('Whatever You Like', 'T.I.', '2000s_hits', 2008, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'Southern rap']),
('Live Your Life', 'T.I.', '2000s_hits', 2008, 'empowering', 'fast', ARRAY['hip hop', 'rap', 'anthem']),
('Paper Planes', 'M.I.A.', '2000s_hits', 2008, 'energetic', 'fast', ARRAY['alternative', 'hip hop', 'indie']),
('Disturbia', 'Rihanna', '2000s_hits', 2008, 'dark', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Take a Bow', 'Rihanna', '2000s_hits', 2008, 'melancholy', 'slow', ARRAY['pop', 'R&B', 'ballad']),
('Love in This Club', 'Usher', '2000s_hits', 2008, 'smooth', 'mid', ARRAY['R&B', 'hip hop soul']),
('4 Minutes', 'Madonna', '2000s_hits', 2008, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Viva la Vida', 'Coldplay', '2000s_hits', 2008, 'uplifting', 'fast', ARRAY['alternative rock', 'baroque pop']),
('The Bleeding', 'Five Finger Death Punch', '2000s_hits', 2008, 'intense', 'fast', ARRAY['heavy metal', 'hard rock']),
('American Boy', 'Estelle', '2000s_hits', 2008, 'upbeat', 'fast', ARRAY['R&B', 'hip hop', 'pop']),
('Bleeding Love', 'Leona Lewis', '2000s_hits', 2008, 'romantic', 'slow', ARRAY['pop', 'R&B', 'ballad']),
('Damaged', 'Danity Kane', '2000s_hits', 2008, 'smooth', 'slow', ARRAY['R&B', 'pop']),
('I Kissed a Girl', 'Katy Perry', '2000s_hits', 2008, 'fun', 'mid', ARRAY['pop', 'dance pop', 'electropop']),
('Hot N Cold', 'Katy Perry', '2000s_hits', 2008, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Love Story', 'Taylor Swift', '2000s_hits', 2008, 'romantic', 'mid', ARRAY['country pop', 'pop', 'teen pop']),
('You Belong with Me', 'Taylor Swift', '2000s_hits', 2008, 'upbeat', 'mid', ARRAY['country pop', 'pop', 'teen pop']),
('Shake It', 'Metro Station', '2000s_hits', 2008, 'energetic', 'fast', ARRAY['pop rock', 'electropop', 'synth pop']),

-- 2009
('Poker Face', 'Lady Gaga', '2000s_hits', 2009, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Just Dance', 'Lady Gaga', '2000s_hits', 2009, 'energetic', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Paparazzi', 'Lady Gaga', '2000s_hits', 2009, 'dark', 'mid', ARRAY['pop', 'electropop', 'glam pop']),
('I Gotta Feeling', 'Black Eyed Peas', '2000s_hits', 2009, 'uplifting', 'fast', ARRAY['pop', 'dance pop', 'hip hop pop']),
('Boom Boom Pow', 'Black Eyed Peas', '2000s_hits', 2009, 'energetic', 'fast', ARRAY['pop', 'hip hop pop', 'electropop']),
('Right Round', 'Flo Rida', '2000s_hits', 2009, 'energetic', 'fast', ARRAY['hip hop', 'dance pop', 'electropop']),
('Run This Town', 'Jay-Z', '2000s_hits', 2009, 'intense', 'fast', ARRAY['hip hop', 'rap', 'anthem']),
('Empire State of Mind', 'Jay-Z', '2000s_hits', 2009, 'uplifting', 'mid', ARRAY['hip hop', 'rap', 'anthem']),
('Down', 'Jay Sean', '2000s_hits', 2009, 'smooth', 'mid', ARRAY['R&B', 'pop', 'hip hop soul']),
('Already Gone', 'Kelly Clarkson', '2000s_hits', 2009, 'empowering', 'mid', ARRAY['pop rock', 'pop', 'ballad']),
('Use Somebody', 'Kings of Leon', '2000s_hits', 2009, 'melancholy', 'mid', ARRAY['indie rock', 'alternative rock']),
('Sex on Fire', 'Kings of Leon', '2000s_hits', 2009, 'intense', 'fast', ARRAY['indie rock', 'alternative rock']),
('You Found Me', 'The Fray', '2000s_hits', 2009, 'melancholy', 'mid', ARRAY['alternative rock', 'piano rock']),
('Halo', 'Beyoncé', '2000s_hits', 2009, 'uplifting', 'slow', ARRAY['pop', 'R&B', 'ballad']),
('Sweet Dreams', 'Beyoncé', '2000s_hits', 2009, 'dark', 'fast', ARRAY['pop', 'dance pop', 'electropop']),
('Fire Burning', 'Sean Kingston', '2000s_hits', 2009, 'upbeat', 'fast', ARRAY['dancehall', 'pop', 'dance']),
('Birthday Sex', 'Jeremih', '2000s_hits', 2009, 'smooth', 'slow', ARRAY['R&B', 'hip hop soul']),
('Forever', 'Drake', '2000s_hits', 2009, 'intense', 'fast', ARRAY['hip hop', 'rap', 'anthem']),
('Best I Ever Had', 'Drake', '2000s_hits', 2009, 'smooth', 'mid', ARRAY['hip hop', 'rap', 'R&B']);
